jobs:
  build:
    machine: true
    docker:
      - image: circleci/node:10.16.3
    steps:
     - checkout
     - run:
          name: Update NPM
          command: "sudo npm install -g npm@5"
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
     - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
     - run: |
        name: Generate Report
        echo $myPageSize
        docker run -t -e PAGE_SIZE=$myPageSize -v $(pwd):/collection postman/newman run "/collection/Test Collection.postman_collection.json" -e "/collection/Test Env.postman_environment.json"-r htmlextra --reporter-htmlextra-export "/collection/newman" --env-var pageSize=$myPageSize
     - store_artifacts:
          path: ~/collection/newman 
        
workflows:
  version: 2
  nightly:
    triggers:
      - schedule:
          cron: "0,5,10,55 * * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build

