jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: |
          echo $myPageSize
          docker run -e PAGE_SIZE=$myPageSize -t -v /tmp/artifacts:/temp -v $(pwd):/collection node:12-slim /bin/bash /collection/setup.sh $myPageSize
      - store_artifacts:
          path: /tmp/artifacts
        

