jobs:
  build:
    machine: true
    steps:
     - checkout
     - run: |
        echo $(env)
        docker run -t -e PAGE_SIZE=${myPageSize} -v $(pwd):/collection postman/newman run "/collection/Test Collection.postman_collection.json" -e "/collection/Test Env.postman_environment.json" --env-var pageSize=5
        
        
workflows:
  version: 2
  nightly:
    triggers:
      - schedule:
          cron: "15 1 24 2 Thu"
          filters:
            branches:
              only:
                - master
    jobs:
      - build

