jobs:
  build:
    machine: true
    steps:
     - checkout
     - run: |
        echo $(env)
        docker run -t --entrypoint=/usr/bin/env -e PAGE_SIZE=${myPageSize} -v $(pwd):/collection postman/newman /usr/bin/env


