jobs:
  build:
    machine: true
    environment:
      MY_PAGE_SIZE: $myPageSize
    steps:
     - checkout
     - run: |
        echo $(env)
        docker run -t --entrypoint=/bin/sh -e PAGE_SIZE=${MY_PAGE_SIZE} -v $(pwd):/collection postman/newman env


