jobs:
  build:
    machine: true
    steps:
     - checkout
     - run: |
        echo $myPageSize
        docker run -t -e PAGE_SIZE=$myPageSize -v $(pwd):/collection postman/newman run "/collection/Test Collection.postman_collection.json" -e "/collection/Test Env.postman_environment.json" --env-var pageSize=$myPageSize
        
        
workflows:
  version: 2
  nightly:
    triggers:
      - schedule:
          cron: "0,5,10,15,20,25,30,35,40,45,50,55 * * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build

